#!/bin/sh

[ ! -d /run/runit.david ] && \
	mkdir -p /run/runit.david && \
	chown david:david /run/runit.david

export HOME=/home/david
groups=$(id -Gn david | tr ' ' ':')

exec chpst -u "david:$groups" sh -l -c "exec runsvdir /home/david/service" david
