[global]
   workgroup = WORKGROUP
   server string = %h server (Samba %v)
   server role = standalone server
   security = user
   passdb backend = tdbsam
   map to guest = never

   bind interfaces only = yes
   interfaces = lo eth0
   hosts allow = 127. 192.168.178.
   hosts deny = 0.0.0.0/0

   server min protocol = SMB2
   smb encrypt = desired

   load printers = no
   printing = bsd
   printcap name = /dev/null
   disable spoolss = yes

   logging = file
   log file = /var/log/samba/log.%m
   max log size = 1000

[Photos]
   path = /mnt/media/photos
   valid users = david
   read only = no
   browsable = yes
   create mask = 0664
   directory mask = 0775

[Music]
   path = /mnt/media/music
   valid users = david
   read only = no
   browsable = yes
   create mask = 0664
   directory mask = 0775
