(setq frame-resize-pixelwise t)
(setq frame-inhibit-implied-resize t)
(setq use-dialog-box t)
(setq use-file-dialog nil)
(setq inhibit-splash-screen t)
(setq inhibit-startup-screen t)
(setq inhibit-x-resources t)
(setq inhibit-startup-echo-area-message user-login-name)
(setq inhibit-startup-buffer-menu t)

(menu-bar-mode 0)
(tool-bar-mode 0)
(scroll-bar-mode 0)
