cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'aria2'
brew 'asciidoctor'
brew 'bash'
brew 'bash-completion'
brew 'cabal-install'
brew 'checkbashisms'
brew 'coreutils'
brew 'ctags'
brew 'elinks'
brew 'ghc'
brew 'git'
brew 'gnu-typist'
brew 'gnupg'
brew 'gnutls'
brew 'htop'
brew 'hunspell'
brew 'iftop'
brew 'isync', args: ['with-berkeley-db']
brew 'jq'
brew 'jrnl'
brew 'lockrun'
brew 'macvim', args: ['--with-override-system-vim']
brew 'mailutils'
brew 'mas'
brew 'mpv'
brew 'msmtp'
brew 'neomutt'
brew 'node'
brew 'notmuch'
brew 'nvm'
brew 'onepass'
brew 'openssl'
brew 'pandoc'
brew 'par'
brew 'proselint'
brew 'pstree'
brew 'python'
brew 'readline'
brew 'rename'
brew 'ripgrep'
brew 'shellcheck'
brew 'shfmt'
brew 'terminal-notifier'
brew 'the_silver_searcher'
brew 'tree'
brew 'urlview'
brew 'wget'

cask 'anki'
cask 'calibre'
cask 'dash'
cask 'dropbox'
cask 'flux'
cask 'goldencheetah'
cask 'karabiner-elements'
cask 'mactex'
cask 'omnifocus'
cask 'slack'
cask 'texshop'

# chunkwm
tap 'crisidev/homebrew-chunkwm'
brew 'chunkwm', args: ['HEAD']
tap 'koekeishiya/formulae'
brew 'koekeishiya/formulae/skhd', args: ['HEAD', 'with-logging']

# vim: filetype=ruby
