set nocompatible        " no need to be vi-like

" If compiled with support for autocommands
if has('autocmd')       
  filetype on           " enable file type detection
  filetype indent on    " load filetype-specific indentation files
  filetype plugin on

  " Syntax of these languages is fussy over tabs Vs spaces
  autocmd FileType make setlocal ts=8 sts=8 sw=8 noexpandtab
  autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab

  " Customisations based on house style (arbitrary)
  autocmd FileType html       setlocal ts=2 sts=2 sw=2 expandtab
  autocmd FileType css        setlocal ts=2 sts=2 sw=2 expandtab
  autocmd FileType javascript setlocal ts=4 sts=4 sw=4 expandtab
endif

syntax enable           " switch on syntax highlighting
set background=dark

if has('termguicolors')
  set termguicolors       " use 24-bit colour
endif

set expandtab           " use spaces instead of a tab character
set tabstop=4
set softtabstop=4
set shiftwidth=4
set wildmenu            " use a menu for command-line completion
set incsearch           " use incremental searching
set textwidth=78        " wrap lines at this column
set listchars=tab:▸\ ,eol:¬     " symbols to indicate tabs and eols

" Spelling
set spelllang=en_au
set spellfile=~/.vim/spell/en.utf-8.add

" vim-plug
call plug#begin('~/.vim/plugged')       " location of vim-plug plugins
Plug 'zhou13/vim-easyescape'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-commentary'
Plug 'tommcdo/vim-lion'
Plug 'airblade/vim-gitgutter'
Plug 'morhetz/gruvbox'
call plug#end()

" Enable use of both jk and kj for <ESC>.
let g:easyescape_chars = { "j": 1, "k": 1 }
let g:easyescape_timeout = 100
cnoremap jk <ESC>
cnoremap kj <ESC>

let g:gruvbox_italic=1
let g:gruvbox_sign_column='bg0'
let g:gruvbox_improved_warnings=1
colorscheme gruvbox

highlight StatusLine   guifg='#282828' guibg='#d5c4a1'
highlight StatusLineNC guifg='#282828' guibg='#928374'
" highlight Search       ctermfg=15  ctermbg=58  
" highlight Default      ctermfg=1
highlight GitGutterAdd          ctermfg=245 ctermbg=235 
highlight GitGutterChange       ctermfg=245 ctermbg=235 
highlight GitGutterDelete       ctermfg=245 ctermbg=235
highlight GitGutterChangeDelete ctermfg=245 ctermbg=235
" highlight EndOfBuffer           guifg='#3c3836' guibg='#282828'

set statusline=%=%P\ %f\ %m
set fillchars=vert:\ ,stl:\ ,stlnc:\ 
set laststatus=2
set noshowmode
