" If compiled with support for autocommands
if has('autocmd')       
  filetype on           " enable file type detection
  filetype plugin on

  " Syntax of these languages is fussy over tabs Vs spaces
  autocmd FileType make setlocal ts=8 sts=8 sw=8 noexpandtab
  autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab

  " Customisations based on house style (arbitrary)
  autocmd FileType html       setlocal ts=2 sts=2 sw=2 expandtab
  autocmd FileType css        setlocal ts=2 sts=2 sw=2 expandtab
  autocmd FileType javascript setlocal ts=4 sts=4 sw=4 expandtab
endif

set background=dark

if has('termguicolors')
  set termguicolors       " use 24-bit colour
endif

set autoindent          " new line copies previous line's indentation
set softtabstop=4       " number of spaces pressing <Tab> counts for
set shiftwidth=4        " number of spaces for each step of indent
set expandtab           " use spaces instead of a tab character
set number              " display line numbers
set wildmenu            " use a menu for command-line completion
set incsearch           " use incremental searching
set textwidth=78        " wrap lines at this column
set listchars=tab:▸\ ,eol:¬     " symbols to indicate tabs and eols
set laststatus=2
set statusline=%=%P\ %f\ %m
" set fillchars=vert:\ ,stl:\ ,stlnc:\ 

" Spelling
set spelllang=en_au
set spellfile=~/.vim/spell/en.utf-8.add

" vim-plug
call plug#begin('~/.vim/plugged')       " location of vim-plug plugins
Plug 'zhou13/vim-easyescape'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-commentary'
Plug 'tommcdo/vim-lion'
Plug 'airblade/vim-gitgutter'
Plug 'chriskempson/base16-vim'
call plug#end()

" Enable use of both jk and kj for <ESC>.
let g:easyescape_chars = { "j": 1, "k": 1 }
let g:easyescape_timeout = 100
cnoremap jk <ESC>
cnoremap kj <ESC>

colorscheme base16-twilight
