#!/bin/sh

bspc monitor -d I II III IV

bspc config border_width          1
bspc config window_gap            2
bspc config split_ratio           0.5
bspc config focus_follows_pointer true

bspwm_config_colors

polybar_start
