#!/bin/sh

# Truncate a couple of common commands that are used herein.
_bc() {
	bspc config "$@"
}

_check() {
	command -v "$1" >/dev/null
}

# Visual options
# ==============
#
# Things to bear in mind about certain configurations:
#
# 1. single_monocle true == Does not recognise receptacles, so if you
#    have a single window and insert a receptacle, the window will
#    remain in monocle view.  Desired behaviour is to tile accordingly.
# 2. borderless_monocle true == Smart borders are bad in multi-monitor
#    setups because you cannot tell which window has focus when
#    a monocle exists on each monitor.  Single monitor is okay.
# 3. ignore_ewmh_focus true == This is very opinionated as it completely
#    prevents focus stealing.  Adapt accordingly.
# 4. pointer_modifier mod1 == enables mouse actions while holding down
#    the Alt key (see below---bonus: the following two also work in the
#    popular desktop environments).
# 5. pointer_action1 move == Alt + Right Click allows you to drag
#    a floating window.  Also works for switching the position of tiled
#    windows, if that is your thing.
# 6. pointer_action2 resize_side == Alt + Left Click allows you to
#    resize the nearest side of the focused window.  Works for both
#    tiled and floating windows.

_bc initial_polarity second_child
_bc border_width 1
_bc window_gap 2
_bc split_ratio 0.50
_bc single_monocle false
_bc borderless_monocle false
_bc gapless_monocle true
_bc focus_follows_pointer true
_bc pointer_follows_monitor true
_bc pointer_modifier mod1
_bc pointer_action1 move
_bc pointer_action2 resize_side
_bc ignore_ewmh_focus false
_bc automatic_scheme longest_side

for i in top right bottom left; do
	_bc "${i}"_monocle_padding 0
done
unset i

# window rules
_check bspwm_external_rules &&
	_bc external_rules_command "$(command -v bspwm_external_rules)"

# Load colour settings.
. "$HOME/.config/bspwm/bspwm_colours"

bspc monitor -d 1 2 3 4
bspc desktop -f 1

# autostart
# =========

# The hotkey daemon that handles all custom key bindings, including the
# ones that control BSPWM.
_check sxhkd && sxhkd -c "$HOME/.config/sxhkd/sxhkdrc" "$HOME/.config/sxhkd/sxhkdrc_bspwm" &

# Launch my custom Lemonbar implementation (the system panel).
_check melonpanel && melonpanel
