#!/bin/sh

# Define desktop[s] [per monitor].
bspwm_conf_desktops

bspc config border_width          2
bspc config window_gap            2
bspc config split_ratio           0.5
bspc config focus_follows_pointer true

bspwm_conf_colors

polybar_start
