-- Monotone color scheme
local lexers = vis.lexers

lexers.STYLE_DEFAULT = 'default'
lexers.STYLE_NOTHING = 'default'
lexers.STYLE_CLASS = ''
lexers.STYLE_COMMENT = 'fore:#6e6e6e,italics'
lexers.STYLE_CONSTANT = ''
lexers.STYLE_DEFINITION = ''
lexers.STYLE_ERROR = 'fore:red'
lexers.STYLE_FUNCTION = ''
lexers.STYLE_KEYWORD = ''
lexers.STYLE_LABEL = ''
lexers.STYLE_NUMBER = ''
lexers.STYLE_OPERATOR = ''
lexers.STYLE_REGEX = ''
lexers.STYLE_STRING = 'fore:#5f875f'
lexers.STYLE_PREPROCESSOR = ''
lexers.STYLE_TAG = ''
lexers.STYLE_TYPE = ''
lexers.STYLE_VARIABLE = ''
lexers.STYLE_WHITESPACE = ''
lexers.STYLE_EMBEDDED = ''
lexers.STYLE_IDENTIFIER = ''

lexers.STYLE_LINENUMBER = ''
lexers.STYLE_LINENUMBER_CURSOR = lexers.STYLE_LINENUMBER
lexers.STYLE_CURSOR = 'reverse'
lexers.STYLE_CURSOR_PRIMARY = 'back:blue'
lexers.STYLE_CURSOR_LINE = ''
lexers.STYLE_COLOR_COLUMN = ''
lexers.STYLE_SELECTION = 'back:#585858'
lexers.STYLE_STATUS = 'fore:#6c6c6c,back:#444444'
lexers.STYLE_STATUS_FOCUSED = 'fore:default,back:#585858'
lexers.STYLE_SEPARATOR = ''
lexers.STYLE_INFO = lexers.STYLE_DEFAULT..',bold'
lexers.STYLE_EOF = lexers.STYLE_COMMENT
