#!/bin/sh
#
# Handler for sxiv key events.  In sxiv, when Ctrl-x <key> is pressed, this
# handler is invoked. It receives <key> and a list of filenames corresponding
# to tagged images.

case "$1" in
"C-d")
	# Delete tagged images.
	while read -r file; do
		mv "$file" ~/tmp/
	done
	;;
esac
