#!/bin/sh
#
# This hook is invoked by the `new’ command after new messages have been
# imported into the database and initial tags have been applied. The
# hook will not be run if there have been any errors during the scan or
# import.

# For the configuration of `afew’, see ~/.config/afew/config
afew --tag --new

notmuch tag -inbox +lists +list/great-conversation \
        -- to:great-conversation@googlegroups.com \
           or to:GreatConversation@yahoogroups.com

notmuch tag -inbox +lists +list/emacs-humanities \
        -- from:emacs-humanities@gnu.org or to:emacs-humanities@gnu.org

notmuch tag -inbox +lists +list/notmuch \
        -- from:notmuch@notmuchmail.org or to:notmuch@notmuchmail.org

# Quoting is needed to ensure “~” is interpreted literally.
notmuch tag -inbox +lists +list/emacs-paris \
        -- 'from:"~bzg/emacsfr@lists.sr.ht"' \
           or 'to:"~bzg/emacsfr@lists.sr.ht"'

notmuch tag -inbox +lists +list/prot-dotfiles \
        -- 'from:"~protesilaos/dotfiles@lists.sr.ht"' \
           or 'to:"~protesilaos/dotfiles@lists.sr.ht"'

notmuch tag -inbox +lists +list/denote \
        -- 'from:"~protesilaos/denote@lists.sr.ht"' \
           or 'to:"~protesilaos/denote@lists.sr.ht"'

notmuch tag -inbox +lists +list/prot-general \
        -- 'from:"~protesilaos/general-issues@lists.sr.ht"' \
           or 'to:"~protesilaos/general-issues@lists.sr.ht"'

notmuch tag -inbox +lists +list/cursory \
        -- 'from:"~protesilaos/cursory@lists.sr.ht"' \
           or 'to:"~protesilaos/cursory@lists.sr.ht"'

notmuch tag -inbox +lists +list/modus-themes \
        -- 'from:"~protesilaos/modus-themes@lists.sr.ht"' \
           or 'to:"~protesilaos/modus-themes@lists.sr.ht"'

notmuch tag -inbox +lists +list/lin \
        -- 'from:"~protesilaos/lin@lists.sr.ht"' \
           or 'to:"~protesilaos/lin@lists.sr.ht"'

notmuch tag -inbox +lists +list/fontaine \
        -- 'from:"~protesilaos/fontaine@lists.sr.ht"' \
           or 'to:"~protesilaos/fontaine@lists.sr.ht"'

notmuch tag -inbox +lists +list/pulsar \
        -- 'from:"~protesilaos/pulsar@lists.sr.ht"' \
           or 'to:"~protesilaos/pulsar@lists.sr.ht"'

notmuch tag -inbox +lists +list/logos \
        -- 'from:"~protesilaos/logos@lists.sr.ht"' \
           or 'to:"~protesilaos/logos@lists.sr.ht"'
