#!/bin/sh
#
# This hook is invoked by the `new’ command after new messages have been
# imported into the database and initial tags have been applied. The
# hook will not be run if there have been any errors during the scan or
# import.

# For the configuration of `afew’, see ~/.config/afew/config
afew --tag --new

# First, remove inbox tag from all messages not in INBOX folder. This handles
# messages archived in Mail.app.
notmuch tag -inbox -- not folder:gmail/INBOX

# Then add inbox tag to messages that ARE in INBOX folder. This handles messages
# moved back to inbox in Mail.app.
notmuch tag +inbox -- folder:gmail/INBOX

# Tag Gmail folders appropriately
notmuch tag +sent -inbox            -- folder:'"gmail/[Gmail]/Sent Mail"'
notmuch tag +draft -inbox           -- folder:'"gmail/[Gmail]/Drafts"'
notmuch tag +deleted -inbox -unread -- folder:'"gmail/[Gmail]/Bin"'
notmuch tag +spam -inbox -unread    -- folder:'"gmail/[Gmail]/Spam"'
notmuch tag +flagged                -- folder:'"gmail/[Gmail]/Starred"'

# Remove inbox tag from All Mail to avoid duplicates in inbox view
notmuch tag -inbox \
		-- folder:'"gmail/[Gmail]/All Mail"' and not folder:gmail/INBOX

# Handle mailing lists

notmuch tag -inbox +lists +list/great-conversation \
	-- to:great-conversation@googlegroups.com \
	   or to:GreatConversation@yahoogroups.com

notmuch tag -inbox +lists +list/emacs-humanities \
	-- from:emacs-humanities@gnu.org or to:emacs-humanities@gnu.org

# Quoting is needed to ensure “~” is interpreted literally.
notmuch tag -inbox +lists +list/emacs-paris \
	-- 'from:"~bzg/emacsfr@lists.sr.ht"' or 'to:"~bzg/emacsfr@lists.sr.ht"'

# Signal the window manager status bar updater.
kill -SIGRTMIN+1 "$(cat /tmp/mtstatus.pid)"
