#!/bin/sh

# post-new --- Notmuch rules that run after notmuch new

# remove "unread" from "replied"
notmuch tag -unread -new -- tag:replied

# tag all "new" messages "inbox" and "unread"
notmuch tag +inbox +unread -new -- tag:new

# tag my replies as "sent"
notmuch tag -new -unread +archived +sent -- '(from:"david@daporter.net*" not to:"david@daporter.net*" not tag:list)'

# mailing lists
notmuch tag -inbox +list +emacs -- from:emacs-humanities@gnu.org or to:emacs-humanities@gnu.org not to:emacs-humanities-owner@gnu.org
notmuch tag -inbox +list +books -- from:great-conversation@googlegroups.com or to:great-conversation@googlegroups.com

# include mailing lists sent to me into the "inbox"
notmuch tag +inbox -- '(to:"david@daporter.net" tag:list)'
